### ISSUE TITLE
Feature Request: Convert BNP to standalone/console mod

### ISSUE THREAD

**Issue by jordanbtucker** [linktlh/bnptool#2]
BCML has a feature that converts a BNP file to a standalone ZIP file for use with Cemu or consoles. It would be great if that feature could be included in bnptool since it would streamline the process of creating cross-platform mods.

A short example of the workflow could be:

```bash
# Create the BNP
bnptool create --name "Linkle Mod - Dialogue Fix" --version 1.5.1 -o ./dist/LinkleModDialogFix_v1_5_1.bnp ./src

# Convert the BNP to standalone
bnptool convert -o ./dist/LinkleModDialogFix_v1_5_1.zip ./dist/LinkleModDialogFix_v1_5_1.bnp
```

**Comment by linktlh** [comment]
Hmm. let me see what I can do.

**Comment by jordanbtucker** [comment]
It looks like `bcml.dev` has a [`convert_mod`](https://github.com/NiceneNerd/BCML/blob/e4b2f4ceedafdcf40f468849afdb1648d0b322aa/bcml/dev.py#L573) function, so it seems like it could be implemented in the same way `bnp_create` uses `bcml.dev.create_bnp_mod`.

**Comment by linktlh** [comment]
[convert_mod](https://github.com/NiceneNerd/BCML/blob/e4b2f4ceedafdcf40f468849afdb1648d0b322aa/bcml/dev.py#L573) is used to convert between platforms [eg Wii U -> Switch] not to stand alone.

**Comment by jordanbtucker** [comment]
Oh, my mistake. Looks like it might be [`convert_bnp`](https://github.com/NiceneNerd/BCML/blob/ba14fbb8c91f9664ba2c9f44674d50c1431f712c/bcml/_api.py#L606) instead.

**Comment by linktlh** [comment]
The exact function that handles that is [bnp_to_gfx](https://github.com/NiceneNerd/BCML/blob/ba14fbb8c91f9664ba2c9f44674d50c1431f712c/bcml/_api.py#L701)

convert_bnp handles attempting to convert an old BNP to the new BNP format.

the issue being that doesn't support a bnp parameter, so I'd have to remake the function itself.

edit: fixed markdown

**Comment by jordanbtucker** [comment]
I see. Yeah, it calls an Open File dialog. Looks like you have this handled, so I'll stop bothering you and let the expert work!

**Comment by linktlh** [comment]
See 13590a53be1be7501530c1dc7a9f3da5c5faa2a4
